package com.hzblogs.dao;

import com.hzblogs.bean.UserPhoto;

public interface UserPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int insert(UserPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int insertSelective(UserPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    UserPhoto selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int updateByPrimaryKeySelective(UserPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int updateByPrimaryKey(UserPhoto record);
}