package com.hzblogs.dao;

import com.hzblogs.bean.AdminPhoto;

public interface AdminPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_photo
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_photo
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int insert(AdminPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_photo
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int insertSelective(AdminPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_photo
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    AdminPhoto selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_photo
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int updateByPrimaryKeySelective(AdminPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_photo
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int updateByPrimaryKey(AdminPhoto record);
}