package com.hzblogs.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hzblogs.bean.Comment;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated Tue Jul 30 16:35:44 CST 2021
     */
    int deleteByPrimaryKey(Integer coId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated Tue Jul 30 16:35:44 CST 2021
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated Tue Jul 30 16:35:44 CST 2021
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated Tue Jul 30 16:35:44 CST 2021
     */
    Comment selectByPrimaryKey(Integer coId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated Tue Jul 30 16:35:44 CST 2021
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated Tue Jul 30 16:35:44 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated Tue Jul 30 16:35:44 CST 2021
     */
    int updateByPrimaryKey(Comment record);
    /**
     *  根据文章id 查询评论信息总数
     * @param coArticleid
     * @return int
     */
	int selectCountByCoArticleid(Integer coArticleid);
	/**
	 * 根据文章id 查询评论信息 ，带分页
	 * @param coArticleid 文章id
	 * @param begin 从哪开始
	 * @param recordSize 偏移量
	 * @return List<Comment>
	 */
	List<Comment> selectByCoArticleid(@Param("coArticleid")Integer coArticleid, @Param("begin")Integer begin, @Param("recordSize")Integer recordSize);
	/**
	 * 根据文章id 查询评论信息
	 * @param articleId
	 * @return List<Comment>
	 */
	List<Comment> selectByarticleId(Integer articleId);
	/**
	 * 根据文章id 删除评论
	 * @param articleId
	 */
	void deleteByarticleId(Integer articleId);
}