package com.hzblogs.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hzblogs.bean.Message;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_info
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    int deleteByPrimaryKey(Integer meId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_info
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_info
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_info
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    Message selectByPrimaryKey(Integer meId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_info
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_info
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_info
     *
     * @mbg.generated Sun Jul 28 08:59:57 CST 2021
     */
    int updateByPrimaryKey(Message record);
    /**
     * 根据留言id 查询留言
     * @param meId
     * @return Message
     */
	Message selectByMeId(Integer meId);
	/**
	 * 根据被留言者id 查询留言信息的总数
	 * @param meUserid
	 * @return int
	 */
	int selectCountByUserId(Integer meUserid);
	/**
	 * 根据被留言者id 查询留言信息，带分页,根据时间降序
	 * @param meUserid 被留言者
	 * @return List<Message>
	 */
	List<Message> selectByMeUserid(@Param("meUserid")Integer meUserid,@Param("begin") Integer begin,@Param("recordSize") Integer recordSize);
	
}