package com.hzblogs.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hzblogs.bean.PhotoAlbums;

public interface PhotoAlbumsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photoalbums_info
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    int deleteByPrimaryKey(Integer paId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photoalbums_info
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    int insert(PhotoAlbums record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photoalbums_info
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    int insertSelective(PhotoAlbums record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photoalbums_info
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    PhotoAlbums selectByPrimaryKey(Integer paId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photoalbums_info
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    int updateByPrimaryKeySelective(PhotoAlbums record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photoalbums_info
     *
     * @mbg.generated Sun Jul 21 10:19:03 CST 2021
     */
    int updateByPrimaryKey(PhotoAlbums record);
    /**
     * 根据 相册id和所属用户id查询相册信息
     * @param paId
     * @param paUserid
     * @return PhotoAlbums
     */
	PhotoAlbums selectByPaidAndUseid(@Param("paId")Integer paId, @Param("paUserid")Integer paUserid);
	/**
	 * 	根据用户id查询相册信息,带分页
	 * @param paUserid
	 * @return List<PhotoAlbums>
	 */
	List<PhotoAlbums> selectByPaUserid(@Param("paUserid")Integer paUserid,@Param("begin")Integer begin,@Param("recordSize")Integer recordSize);
	/**
	 * 根据用户id查询，相册数量
	 * @param paUserid
	 * @return int
	 */
	int selectCountByPaUserid(Integer paUserid);
	/**
	 * 根据用户id查询相册信息,不带分页
	 * @param paUserid
	 * @return List<PhotoAlbums>
	 */
	List<PhotoAlbums> selectAlbumsByPaUserid(Integer paUserid);
	/**
	 * 根据相册id和用户id，更新相册的封面图片
	 * @param photoAlbums
	 * @return int
	 */ 
	int updateBypaIdAnduserid(PhotoAlbums photoAlbums);
	/**
	 * 根据相册id，更新相册的封面图片为空
	 * @param paId
	 * @param paCoverimg
	 * @return int
	 */
	int updateCoverPhotobyNull(@Param("paId")Integer paId,@Param("paCoverimg") String paCoverimg);
}