package com.hzblogs.dao;

import com.hzblogs.bean.UserRecentlyLogin;

public interface UserRecentlyLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recentlylogin
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recentlylogin
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int insert(UserRecentlyLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recentlylogin
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int insertSelective(UserRecentlyLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recentlylogin
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    UserRecentlyLogin selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recentlylogin
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int updateByPrimaryKeySelective(UserRecentlyLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recentlylogin
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int updateByPrimaryKey(UserRecentlyLogin record);
}