package com.hzblogs.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hzblogs.bean.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    User selectByPrimaryKey(Integer id);
    
    User selectByuserLogin(String userLogin);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Jul 04 10:53:21 CST 2021
     */
    int updateByPrimaryKey(User record);
    /**
     * 根据userid更改用户主题
     * @param user
     * @return int
     */
	int updateByUserTheme(User user);
	/**
	 * 根据userid更改用户留言寄语
	 * @param userSendWord
	 * @param id
	 * @return int
	 */
	int updateSendWordByUserid(@Param("userSendWord")String userSendWord,@Param("id") Integer id);
}